services:
  redpanda:
    image: redpandadata/redpanda:v24.2.7
    container_name: rtdp-redpanda
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=INTERNAL://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rtdp-postgres
    environment:
      POSTGRES_USER: rtdp
      POSTGRES_PASSWORD: rtdp
      POSTGRES_DB: realtime_platform
    ports:
      - "15432:5432"
    volumes:
      - rtdp_postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
    container_name: rtdp-api
    command: rtdp-api
    environment:
      DATABASE_URL: postgresql://rtdp:rtdp@postgres:5432/realtime_platform
      SERVICE_NAME: rtdp-api
      SERVICE_VERSION: 0.1.0
      ENVIRONMENT: docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  producer:
    build:
      context: .
    container_name: rtdp-producer
    command: rtdp-producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    depends_on:
      - redpanda

  consumer:
    build:
      context: .
    container_name: rtdp-consumer
    command: rtdp-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      DATABASE_URL: postgresql://rtdp:rtdp@postgres:5432/realtime_platform
    depends_on:
      - redpanda
      - postgres


volumes:
  rtdp_postgres_data:
